### ISSUE TITLE
"`"で囲まれたインラインコードの中身を翻訳するか

### ISSUE THREAD

**Issue by s3-odara** [nostr-jp/nips-ja#127]
インラインコードを結構装飾ぐらいの感覚で使っているNIPがある気がするので、場合によって翻訳したほうが読みやすいかも。

**Comment by Hakkadaikon** [comment]
私はコードブロック内の英訳も翻訳することに**賛成**です。
例えば、以下はNIP-01のコードブロックですが、割と英文が入っています。(特にsigの説明とか。)

```jsonc
{
  "id": <32-bytes lowercase hex-encoded sha256 of the serialized event data>,
  "pubkey": <32-bytes lowercase hex-encoded public key of the event creator>,
  "created_at": <unix timestamp in seconds>,
  "kind": <integer between 0 and 65535>,
  "tags": [
    [<arbitrary string>...],
    // ...
  ],
  "content": <arbitrary string>,
  "sig": <64-bytes lowercase hex of the signature of the sha256 hash of the serialized event data, which is the same as the "id" field>
}
```

**Comment by s3-odara** [comment]
mdnの翻訳ガイドでもコードブロックはコメント、文字列、出力表現を翻訳するように言ってるのでこれを参考に書き換えても良さそう

https://github.com/mdn/translated-content/blob/main/docs/README.md#localizing-code-blockshttps://github.com/mdn/translated-content/blob/main/docs/README.md#localizing-code-blocks
