### ISSUE TITLE
NIP-26 translation issue

### ISSUE THREAD

**Issue by heguro** [nostr-jp/nips-ja#19]
指摘忘れを見つけたため issue で失礼します。

現時点の翻訳:
https://github.com/nostr-jp/nips-ja/blob/e5fb584a5b57cda1b5ff40cc8a2ff0b915c181f3/26.md?plain=1#L110

※参考: 原文
https://github.com/nostr-protocol/nips/blob/d85f9269ca300fb3bee627733c8086df4fcff875/26.md?plain=1#L110

> 許可する必要があります。 (SHOULD)

SHOULD なので「必要がある」とまでは行かず「許可するべき」程度がよいのではないかと思ったのですがどうでしょうか。

関連: #2
@s3-odara

**Comment by s3-odara** [comment]
返信遅れました。
ご指摘ありがとうございます。

SHOULDの訳はこの「RFCにおいて要請の程度を示すために用いるキーワード」メモの日本語訳を参考にしました。
https://www.nic.ad.jp/ja/tech/ipa/RFC2119JA.html

ただ、他の日本語訳も見ると「するべきである」のほうが優勢ですかね。
どちらが正当な理由がなければ実装したほうが良いという意図にあっているか判断しかねます。

**Comment by s3-odara** [comment]
https://github.com/nostr-jp/nips-ja/issues/6#issuecomment-1809818268

erechorseさんの見解が出ていたのでこれに合わせます。
