### ISSUE TITLE
NIP-05翻訳のtextlintルール

### ISSUE THREAD

**Issue by s3-odara** [nostr-jp/nips-ja#29]
NIP-05の翻訳で [[サ変名詞]を行うルールに違反している](https://github.com/nostr-jp/nips-ja/pull/15#discussion_r1374377000) のですが、「を行う」が冗長になるのは、
https://www.nhk.or.jp/bunken/summary/kotoba/yougo/pdf/045.pdf
この記事の鉛筆立て作りの例で示されるように前の単語がひとつの名詞かのように考えてしまって「〇〇を要求する」が「〇〇要求を行う」のように冗長になってしまう場合だと思います。

NIP-05の現在の翻訳では「GET要求を行う」が違反しているのですが、これは「GET要求」がひとまとまりの名詞形として扱うのに適当であるために誤検知であると考えています。
「GETリクエストを行う」に変更すると通るようになるのですが、そもそもリクエストもサ変名詞であるために根本的な解決にはなりません。

lintで個別に除外できればそれがいいのですが、できなそうであればtextlint-rule-ja-no-redundant-expressionのdict5をルールから外すのがいいのかなと。

**Comment by s3-odara** [comment]
弱い表現を使わないlintルールも、原文が弱い表現を使っている箇所があるので削除したほうがいいと思います。

**Comment by erechorse** [comment]
textlint-rule-ja-no-redundant-expression(冗長な表現を除外)の件は

https://github.com/textlint-ja/textlint-rule-ja-no-redundant-expression#options

まだテストしていませんが、個別除外は可能そうです。

**Comment by s3-odara** [comment]
ありがとうございます。
