### ISSUE TITLE
ubiquitous language

### ISSUE THREAD

**Issue by Hakkadaikon** [nostr-jp/nips-ja#77]
# 概要
昨日[README翻訳](https://github.com/nostr-jp/nips-ja/pull/76)をレビューした時に思ったのですが、ユビキタス言語 (用語統一の一覧)が欲しいと思いました。

# 例
- Relay, リレー -> リレー
- Client, クライアント -> クライアント

# 記載方法
mdのテーブル形式で、↓ こういう感じでいいと思います。

| 名前(英)        | 名前(日)                   | よくある間違い         | 
| -------------- | --------------------- | ----------------------- | 
| Relay             | リレー                     | Relay                         | 
| Client            | クライアント          | Client                         | 
| interests list  | 興味・関心リスト   | インタレストリスト | 

# 管理について
管理者等は特に決めず、気付いた人が追加・レビューする形でいいと思います。
管理場所についてはWiki or リポジトリに含める のどちらかと思っていますが
個人的にはWiki管理でもいいのではと思っています。

# このissueの完了条件
* ユビキタス言語導入有無の決定
* 導入する場合、たたき台を作って追加 (これは私 (発火大根)がやれます)

まずは、皆さんの意見が聞きたいと思います。

**Comment by Hakkadaikon** [comment]
darashiさんの以下提案とほぼ同義かと。

https://github.com/nostr-jp/nips-ja/issues/6#issuecomment-1791899132

**Comment by gpsnmeajp** [comment]
対訳リストは私も必要性を感じました。
既存の翻訳部分から拾うにしても、結構手間がかかる&見落としやすいので、あるとかなり楽になると思います。

**Comment by penpenpng** [comment]
もし[textlintの設定である程度は対応可能](https://github.com/nostr-jp/nips-ja/issues/6#issuecomment-1791899132)ということであれば機械可読な形式の方が取り回しがいいと思います……が、実際に機能させるには「他にどのような訳例があるか」を列挙する必要がある気がしており、textlintがどれほど有効に働くのかには疑問を持っています。textlintまわりに詳しくないので他の方の意見が聞きたいです。

**Comment by Hakkadaikon** [comment]
以下の記事を見ると、誤った文章表現を記載した際、textlintで警告と任意の警告文を表示できるようです。
https://qiita.com/takasp/items/22f7f72b691fda30aea2

ただ、これとは別に、ユビキタス言語の表はあっても良いのでは、と個人的には思います。
ひとまず仮運用として、Wikiにユビキタス言語の表の骨子だけ作っておきます。
(ひとまずWikiに集めておけばと考えています、正式な運用をどうするかは別途調整)

**Comment by Hakkadaikon** [comment]
仮運用として、Wikiの骨子だけ作りました。
ひとまずここに用語を集めていけたらと考えています。
※他にいい運用があれば、別途提案貰えると助かります

https://github.com/nostr-jp/nips-ja/wiki/NIPs-ユビキタス言語

**Comment by Hakkadaikon** [comment]
discussions機能を有効にし、Wikiの作成をアナウンスしました。
https://github.com/orgs/nostr-jp/discussions/78

**Comment by penpenpng** [comment]
issue の終了条件は満たしているのでこちらは閉じてもよさそうに思いますがどうでしょう @Hakkadaikon

**Comment by Hakkadaikon** [comment]
discussionにリンクを貼ってきました。
本件はクローズします。
