### ISSUE TITLE
NIP-01: Resolve conflicts

### ISSUE THREAD

**Issue by jiftechnify** [nostr-jp/nips-ja#79]
https://github.com/nostr-jp/nips-ja/pull/72 で発生したconflictについて、差分が大きいものについては一旦conflictマーカーを残したままマージさせていただきました。

訳文の更新とconflictの解決をお願いいたします。

**Comment by darashi** [comment]
了解です! :ok_person:

**Comment by darashi** [comment]
resolved by #81
