### ISSUE TITLE
NIP-46: Resolve conflicts

### ISSUE THREAD

**Issue by jiftechnify** [nostr-jp/nips-ja#80]
https://github.com/nostr-jp/nips-ja/pull/72 で発生したconflictについて、差分が大きいものについては一旦conflictマーカーを残したままマージさせていただきました。

訳文の更新とconflictの解決をお願いいたします。

**Comment by s3-odara** [comment]
アサインに気づいていませんでした。ありがとうございます。
コンフリクト解消...というかほぼ書き直しなので翻訳し直しておきました。 #92
